### ISSUE TITLE
Support for Subscribing to Output from Devices

### ISSUE THREAD

**Issue by afawcett** [afawcett/littlebits-connector#1]
Use the recently added support to the Apex LittleBits API (@corycowgill thanks!) to provide a means to declaratively Subscribe to output from the device and invoke platform native #clicksnotcode logic, such as a Headless Flow!

**Comment by afawcett** [comment]
Thought would be to have a **LittleBits Subscriber** object to define the Subscription details and the Flow name to route it to, passing into the Flow via pre-defined (documented) Flow input variables. It might be best to have a Output picklist field, for example having the values of Flow, Object, Apex Class (implementing a global interface). Thus making the subscription definition extensible to allow the event to be emitted in various ways. With the Object option providing a means to simple log the received data in an object as a new record (permitting regular Workflow to be used and ultimatly Flow Triggers).

Some challenges to overcome...
- As per a recent [blog](http://andyinthecloud.com/2014/10/26/calling-flow-from-apex/) of mine its not possible to dynamically state a Flow to execute, thus we may have to leverage the Apex MD API to deploy into the org a generated dispatcher (implements a global interface from the package) to act as a proxy to invoke it.
- Though we can package sites, its probably best to let this be created and managed in the org, again using the Apex MD API (there is a site creation example in the MetadataServiceExamples.cls class).

@corycowgill what do you think?

**Comment by corycowgill** [comment]
Yes we need to package up the creation the Force.com Site / REST Endpoint as part of the Apex MD (I'll take a look this weekend). 

When a URI is subscribed to a device the Cloud API passes a very simple JSON object of subscription parameters including event (amplitude ignition, current, etc) as well as a % and device ID. Note: This JSON payload does not match the documentation (device_id is bit_id) and does not seem to be stable in terms of defiitions. 

We should use JSON serializer to parse that data and pass to the Flow variables or SObject I think. We should use untyped JSON as this payload still seems unstable from littleBits......

**Comment by afawcett** [comment]
RE: Dynamically calling Flows, another option, to avoid hassle of generating test code and deployments etc. Maybe to call Execute Anonymous SOAP API from Apex...

**Comment by afawcett** [comment]
Source code (and a very funny video of @corycowgill) for handling subscription [here](http://littlebits.cc/projects/night-eating-trainer), @corycowgill  'Cough Logger' [here](http://littlebits.cc/projects/cough-logger). Subscription registration code is also [here](https://github.com/afawcett/apex-littlebitsapi/blob/master/src/classes/LittleBits.cls#L130).

**Comment by afawcett** [comment]
@corycowgill just to let you know i've made a start on this, mainly focusing on how to invoke a headless Flow dynamically from the Apex REST resource. As discussed skipping the automation of the site setup for the moment. I'm using your subscribe method on the LittleBits class.

**Comment by afawcett** [comment]
Its alive!!! :+1: 

<img width="1360" alt="screen shot 2015-08-01 at 11 33 22" src="https://cloud.githubusercontent.com/assets/1167760/9021581/38889198-3841-11e5-8e14-f952557231be.png">

**Comment by afawcett** [comment]
I suggest we provide a multi-picklist on the device subscription object that reflects the event names (with more friendly titles perhaps?). Next up a means for the user to state a Flow to invoke and then figure a way of doing this dynamically. Since the platform [does not permit dynamic instantiation of Flow Interview](https://success.salesforce.com/ideaView?id=08730000000DfUCAA0) instances, i'll like work on a code generated factory class (tool can manage this for the user via Apex MD API) to inject into the org that can be then be dynamically instantiated passing the flow name and params....

**Comment by afawcett** [comment]
<img width="918" alt="littlebitsflowsubscription" src="https://cloud.githubusercontent.com/assets/1167760/9025879/1730e778-3910-11e5-9f43-45e2f67eb52b.png">

<img width="1054" alt="screen shot 2015-08-02 at 12 02 36" src="https://cloud.githubusercontent.com/assets/1167760/9025833/aa8656c2-390e-11e5-9ae2-ef3397c05b45.png">

<img width="1176" alt="littlebitsflowouptupt" src="https://cloud.githubusercontent.com/assets/1167760/9025880/1b69254e-3910-11e5-8bc1-a15499164f2b.png">

**Comment by afawcett** [comment]
Ok so initially commit today with the above, more work to do around testing and UI to drive dynamic creation of the LittleBitsFlowFactory class in the subscriber org. I cannot wait to see what folks do with these new features!

**Comment by afawcett** [comment]
Added in release v1.12
