### ISSUE TITLE
Exception when creating the trigger

### ISSUE THREAD

**Issue by fcathala** [afawcett/littlebits-connector#7]
Hi,

When clicking on "Manage Object Trigger" the operation does not complete and I receive the following error message: 

Visualforce Error
lbc.fflib_QueryFactory.InvalidFieldException: Invalid field 'CurrencyIsoCode' for object 'ApexTrigger' 
An unexpected error has occurred. Your solution provider has been notified. (lbc)

This happens on a test org with lots of features activated in particular multi-currencies.

**Comment by afawcett** [comment]
Ah sorry about this, thats a bug. I'll get this sorted.

**Comment by afawcett** [comment]
Fixed in v1.3 package release.
